### ISSUE TITLE
"Not proxy protocol!!" logged to stderr without a way to suppress it.

### ISSUE THREAD

**Issue by jeffreydwalter** [R358/qppp#1]
Hi,

Awesome library! Are you still maintaining it? If so, is there a way to suppress "Not proxy protocol!!"?

Thanks!

**Comment by meganwoods** [comment]
Hi,

Thanks for reaching out.

Yes I would say it was a left over print statement so I have removed it here: 
https://github.com/R358/qppp/commit/f02e5d70f781c3d4598c3bf1c72d091c8fbfc434

Fix has been pushed.

Megan

**Comment by jeffreydwalter** [comment]
Thanks for the quick response!
