### ISSUE TITLE
Seemingly redundant call to conn.Close()?

### ISSUE THREAD

**Issue by jeffreydwalter** [R358/qppp#2]
Hello, me again. :)

Was just perusing the source and noticed that you are potentially calling `conn.Close()` twice if `err != nil` in the following blocks of code:
https://github.com/R358/qppp/blob/master/qppp.go#L186-L195
and
https://github.com/R358/qppp/blob/master/qppp.go#L196-L205

I'm just curious as to why that second call to conn.Close() is needed on lines https://github.com/R358/qppp/blob/master/qppp.go#L193 and https://github.com/R358/qppp/blob/master/qppp.go#L203, respectively.

Thanks!

**Comment by jeffreydwalter** [comment]
To be crystal clear, what I'm asking is why can't you just do this:
```
if bytes.Equal(inp, prefix[:i]) {
			srcAddr, dstAddr, err = parseV1(bufReader, conn)
			if err != nil {
				conn.Close()
			}
			break
		} else if bytes.Equal(inp, v2Magic1[:i]) {
			srcAddr, dstAddr, err = parseV2(bufReader, conn)
			if err != nil {
				conn.Close()
			}
			break
		} else {
```

**Comment by meganwoods** [comment]
Hi,

To be honest I wrote this about the time I started doing golang and looking at it 3 odd years down the track I agree with you the calls are probably redundant.

I have pushed the changes, let me know how you go.

Megan

**Comment by jeffreydwalter** [comment]
Will do. Thank you!
